### ISSUE TITLE
File name is incorrect

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Dynamic-Story-Scripting-with-the-ink-Scripting-Language#1]
https://github.com/PacktPublishing/Dynamic-Story-Scripting-with-the-ink-Scripting-Language/blob/main/Chapter9/Example4/InkStoryPlayerStatisticsScript.cs

Code has: public class InkStoryScript : MonoBehaviour

Just need to update the class name to match the book text

**Comment by videlais** [comment]
Updated. Thanks for catching it.
